create table if not exists territorial_zones (
  zone_number integer primary key check (zone_number between 1 and 8),
  courier_id uuid references couriers(id) on delete set null,
  courier_name text not null,
  courier_phone text,
  total_barrios integer not null default 0,
  total_cantidad_barrios integer not null default 0,
  total_upz integer not null default 0,
  total_localidades integer not null default 0,
  localities_text text not null default '',
  source text not null default 'barrios_zonas_a3',
  updated_at timestamptz not null default now()
);

create table if not exists territorial_neighborhoods (
  id bigint generated by default as identity primary key,
  locality_code text not null,
  locality_name text not null,
  upz_name text not null,
  neighborhood_name text not null,
  zone_number integer not null references territorial_zones(zone_number) on delete cascade,
  courier_name text not null,
  cantidad_barrios integer not null default 1,
  source text not null default 'barrios_zonas_a3',
  updated_at timestamptz not null default now(),
  unique (locality_code, upz_name, neighborhood_name, zone_number)
);

create index if not exists idx_territorial_neighborhoods_zone on territorial_neighborhoods(zone_number);
create index if not exists idx_territorial_neighborhoods_locality on territorial_neighborhoods(locality_code);
create index if not exists idx_territorial_neighborhoods_name on territorial_neighborhoods(neighborhood_name);
